### ISSUE TITLE
noble warning: unknown peripheral 000b570c3d1e

### ISSUE THREAD

**Issue by Kroltez** [futomi/node-thunderboard-react#3]
On the startMonitor Methods after about 11 good sets of data received I keep getting the same error:

```
pi@raspberrypi:~/code/ThunderBoard $ sudo node ExampleB.js

Found Thunder React #15646
Connected Thunder React #15646
Orientation:
alpha :0°
beta :-0.34°
gamma :0.03°
Orientation:
alpha :-0.03°
beta :-0.74°
gamma :0.05°
Orientation:
alpha :-0.06°
beta :-1.14°
gamma :0.08°
Orientation:
alpha :-0.1°
beta :-1.54°
gamma :0.11°
Orientation:
alpha :-0.13°
beta :-1.93°
gamma :0.14°
Orientation:
alpha :-0.16°
beta :-2.33°
gamma :0.17°
Orientation:
alpha :-0.2°
beta :-2.72°
gamma :0.19°
Orientation:
alpha :-0.23°
beta :-3.13°
gamma :0.21°
Orientation:
alpha :-0.26°
beta :-3.52°
gamma :0.24°
Orientation:
alpha :-0.3°
beta :-3.92°
gamma :0.27°
Orientation:
alpha :-0.33°
beta :-4.32°
gamma :0.3°
noble warning: unknown peripheral 000b570c3d1e
```

Also, the board often fails to connect

**Comment by Kroltez** [comment]
Update: I changed the recall time from 5000 to 50000 and that has now not displaying the warning but instead getting stuck in the same loop it is stuck in when the board fails to connect.

**Comment by Kroltez** [comment]
[hcidump11.12OriantationWorksThenFails.txt](https://github.com/futomi/node-thunderboard-react/files/646249/hcidump11.12OriantationWorksThenFails.txt)

**Comment by Kroltez** [comment]
[hcidump14.12CombinationWorksThenFails.txt](https://github.com/futomi/node-thunderboard-react/files/651463/hcidump14.12CombinationWorksThenFails.txt)
[hcidump14.12NoConnection.txt](https://github.com/futomi/node-thunderboard-react/files/651464/hcidump14.12NoConnection.txt)
[hcidump12.12LEDFailsConnection.txt](https://github.com/futomi/node-thunderboard-react/files/651462/hcidump12.12LEDFailsConnection.txt)
[hcidump12.12LEDWorks.txt](https://github.com/futomi/node-thunderboard-react/files/651461/hcidump12.12LEDWorks.txt)

**Comment by Kroltez** [comment]
I'm not getting this error anymore. Not sure what changed....

**Comment by Kroltez** [comment]
I was using a different thunderboard, that is what changed. Still get that error on the first thunderboard!

**Comment by futomi** [comment]
I think that the performance of your BLE receiver is too low or your radio wave environment is too bad. If you have any other BLE receivers, try them. As far as I experienced, cheap BLE receivers likely do not have the ability to tolerate too many data stream.

**Comment by Kroltez** [comment]
I think it could be that my app sometimes sees the name of that thunderboard as Thunder #000012345 rather than Thunder React #12345 Very strange. How can it be advertising 2 names!? That's probably why it thinks it is an unknown peripheral
